import dotenv from 'dotenv'

dotenv.config()

const { SERVER_PORT, SECRET, DB_URL, AZURE_ID_META_DATA, AZURE_TOKEN_ENDPOINT, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_REDIRECT_URL, AZURE_LOGOUT_REDIRECT_URL, AZURE_AD_SUCCESS, AZURE_AD_FAILURE, AZURE_TENANT_ID } = process.env

export default { SERVER_PORT, SECRET, DB_URL, AZURE_ID_META_DATA, AZURE_TOKEN_ENDPOINT, AZURE_CLIENT_ID, AZURE_CLIENT_SECRET, AZURE_REDIRECT_URL, AZURE_LOGOUT_REDIRECT_URL, AZURE_AD_SUCCESS, AZURE_AD_FAILURE, AZURE_TENANT_ID }
